# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'LivoAPP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'lottie-ios'
  pod 'SwiftyBeaver'
  pod 'TextFieldEffects'
  pod 'PasswordTextField'
  pod 'JMMaskTextField-Swift'
  # Pods for LivoAPP

end
